import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Moon, Sun, Monitor, Smartphone } from 'lucide-react';
import { useTheme } from '../context/ThemeContext';
import { usePlatform } from '../hooks/usePlatform';
export default function SettingsPage() {
    const { theme, setTheme } = useTheme();
    const { mode, isAutoDetected, setOverride } = usePlatform();
    return (_jsx("div", { className: "min-h-screen", style: { background: 'var(--bg)', color: 'var(--text)' }, children: _jsxs("main", { className: "container py-8 max-w-xl", children: [_jsx("h1", { className: "font-display text-2xl mb-6", "data-aos": "fade-down", children: "Settings" }), _jsxs("div", { className: "card mb-4", "data-aos": "fade-up", children: [_jsx("h3", { className: "font-semibold mb-3", children: "Appearance" }), _jsxs("div", { className: "flex gap-2", children: [_jsxs("button", { onClick: () => setTheme('light'), className: `flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg border text-sm font-semibold ${theme === 'light' ? 'bg-brand-600 text-white border-brand-600' : 'border-[var(--border)]'}`, children: [_jsx(Sun, { size: 16 }), " Light"] }), _jsxs("button", { onClick: () => setTheme('dark'), className: `flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg border text-sm font-semibold ${theme === 'dark' ? 'bg-brand-600 text-white border-brand-600' : 'border-[var(--border)]'}`, children: [_jsx(Moon, { size: 16 }), " Dark"] })] })] }), _jsxs("div", { className: "card", "data-aos": "fade-up", "data-aos-delay": "80", children: [_jsx("h3", { className: "font-semibold mb-1", children: "Display mode" }), _jsx("p", { className: "text-xs mb-3", style: { color: 'var(--text-muted)' }, children: isAutoDetected ? 'Currently auto-detected from your screen size.' : 'Manually overridden — resize won\'t change this.' }), _jsxs("div", { className: "flex gap-2 mb-2", children: [_jsxs("button", { onClick: () => setOverride('desktop'), className: `flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg border text-sm font-semibold ${mode === 'desktop' ? 'bg-brand-600 text-white border-brand-600' : 'border-[var(--border)]'}`, children: [_jsx(Monitor, { size: 16 }), " Desktop"] }), _jsxs("button", { onClick: () => setOverride('mobile'), className: `flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg border text-sm font-semibold ${mode === 'mobile' ? 'bg-brand-600 text-white border-brand-600' : 'border-[var(--border)]'}`, children: [_jsx(Smartphone, { size: 16 }), " Mobile"] })] }), !isAutoDetected && (_jsx("button", { onClick: () => setOverride(null), className: "text-xs font-semibold hover:opacity-80", children: "Reset to auto-detect" }))] })] }) }));
}
//# sourceMappingURL=Settings.js.map